ALTER TYPE "LiveSessionStatus" ADD VALUE IF NOT EXISTS 'STARTING';
ALTER TYPE "LiveSessionStatus" ADD VALUE IF NOT EXISTS 'RECONNECTING';
ALTER TYPE "LiveSessionStatus" ADD VALUE IF NOT EXISTS 'DISCONNECTED';
ALTER TYPE "LiveSessionStatus" ADD VALUE IF NOT EXISTS 'REPLAY_AVAILABLE';

ALTER TABLE "LiveSession"
ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "reconnectUntil" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "LiveSession_reconnectUntil_idx" ON "LiveSession"("reconnectUntil");
